### ISSUE TITLE
请问，可以直接编译使用吗？

### ISSUE THREAD

**Issue by sdf8057** [ferhung-mtk/rt-n56u#1]

**Comment by ferhung-mtk** [comment]
你是什么型号的路由器？K2P是可以直接编译使用的。推荐使用Ubuntu18.04编译，并安装GCC-5，如果已安装GCC-7，请切换到GCC-5再编译。

**Comment by sdf8057** [comment]
emm，k2p配置文件里的v4.4.X.X是什么驱动？

**Comment by ferhung-mtk** [comment]
7615的无线驱动，版本号为4.4.1.2。
